# -*- encoding: utf-8 -*-
##############################################################################
#
#    Product - Standard Price VAT Included Module for Odoo
#    Copyright (C) 2015-Today GRAP (http://www.grap.coop)
#    @author Sylvain LE GAL (https://twitter.com/legalsylvain)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

- !record {model: product.pricelist, id: pricelist_standard_price_vat_incl}:
    name: Sale Price List based on Cost VAT Included
    type: sale

- !record {model: product.pricelist.version, id: pricelist_version_standard_price_vat_incl}:
    name: Sale Price List Version based on Cost VAT Included
    pricelist_id: pricelist_standard_price_vat_incl

- !record {model: product.pricelist.item, id: pricelist_item_standard_price_vat_incl}:
    name: Sale Price List Item based on Cost VAT Included
    price_version_id: pricelist_version_standard_price_vat_incl
    base: !eval (ref('standard_price_vat_incl'))
    price_discount: 0.0
